replicaCount: 1

image:
  repository: brianpzaide/shipserver
  tag: latest
  pullpolicy: Always

resources:
  requests:
    CPU: 250m
    memory: 64Mi
  limits:
    CPU: 500m
    memory: 128Mi

containerPort: 10000

service:
  port: 10000
  targetPort: 10000
  nodePort: 31179
  protocol: TCP
  type: NodePort