apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipserver
  name: shipserver
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: shipserver
  template:
    metadata:
      labels:
        app: shipserver
    spec:
      containers:
      - image: {{.Values.image.repository}}:{{.Values.image.tag}}
        name: shipserver
        imagePullPolicy: {{.Values.image.pullpolicy}}
        resources:
          requests:
            cpu: {{.Values.resources.requests.CPU}}
            memory : {{.Values.resources.requests.memory}}
          limits:
            cpu: {{.Values.resources.limits.CPU}}
            memory: {{.Values.resources.limits.memory}}
        ports:
        - containerPort: {{.Values.containerPort}}