apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipserver
  name: shipserver
spec:
  ports:
  - port: {{.Values.service.port}}
    protocol: {{.Values.service.protocol}}
    targetPort: {{if .Values.service.targetPort}} {{.Values.service.targetPort}} {{else}} {{.Values.service.port}} {{end}}
    nodePort: {{.Values.service.nodePort}}
  selector:
    app: shipserver
  type: {{.Values.service.type}}